# Plantilla de Extracción y Limpieza de Datos

### 1. Cargar un archivo desde Google Drive

Primero, montaremos Google Drive para acceder a tus archivos.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 2. Configuración de la ruta del archivo

Define aquí la ruta a tu archivo CSV o Excel en Google Drive. Esta variable será usada por las celdas posteriores para cargar los datos.

In [2]:
# Define aquí la ruta a tu archivo CSV o Excel en Google Drive
# Ejemplo: '/content/drive/MyDrive/Kaggle/nombre_de_tu_archivo.csv'
file_path_global = '/content/drive/MyDrive/Kaggle/dummy_hospital_generated.csv'

print(f"Ruta del archivo configurada: {file_path_global}")

Ruta del archivo configurada: /content/drive/MyDrive/Kaggle/dummy_hospital_generated.csv

Ahora, puedes especificar la ruta de tu archivo CSV o Excel. **Asegúrate de reemplazar `'RUTA_A_TU_ARCHIVO.csv'` con la ruta real de tu archivo en Google Drive.**

Por ejemplo, si tu archivo está en `Mi Drive/Carpeta/mi_archivo.csv`, la ruta sería `/content/drive/MyDrive/Carpeta/mi_archivo.csv`.

### 3. Cargar el DataFrame

In [3]:
import pandas as pd

try:
    # Si es un archivo CSV, usa pd.read_csv
    df = pd.read_csv(file_path_global)
    print("Archivo CSV cargado exitosamente.")
    display(df.head())
except FileNotFoundError:
    print(f"Error: El archivo no se encontró en la ruta especificada: {file_path_global}")
    print("Por favor, verifica la ruta y asegúrate de que Google Drive esté montado correctamente.")
    df = None
except Exception as e:
    print(f"Ocurrió un error al cargar el archivo: {e}")
    df = None

Archivo CSV cargado exitosamente.

,Month,Case_No,DOB,Nationality,Gender,DoctorLicense,DoctorName,Doctor Type,Doctor Status,CMI Value,...,Insurance/Payer,InsurancePlanName,Payer Mix,Case type,LOS,Severity,Surgical Mix,Discharge Time,Discharge Before 12PM,Revenue
0,2025-02-01,123517868.0,2002.0,Pakistan,F,ABC123,Dr. Shawn Martin,Consultant,Inactive,1.048,...,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,07:00:00,Yes,548.0
1,2025-10-01,123810649.0,1981.0,Indonesia,F,VBN123,Dr. Peter Novak,Consultant,Active,0.942,...,PureWin Insurance,Basic,Insurance,OP,0.0,2.0,Medical,NaN,NaN,1198.0
2,2025-08-01,123979661.0,1990.0,Egypt,M,FGH123,Dr. Sofia Kim,GP,Active,1.089,...,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,NaN,NaN,586.0
3,2025-06-01,123927914.0,1991.0,Germany,M,HJK123,Dr. Priya Iyer,Specialist,Active,0.970,...,BlueMedic Charity,NaN,Corporate,IP,5.0,1.0,Medical,09:13:00,Yes,28717.0
4,2025-06-01,123605097.0,2000.0,UAE,F,ABC234,Dr. Thomas Muller,Specialist,Active,1.006,...,Nextcare Insurance,NC-Blue,Insurance,IP,4.0,3.0,Medical,13:39:00,No,117129.0

### 4. Revisión inicial del DataFrame

Verifica las dimensiones, los tipos de datos y un resumen estadístico.

In [4]:
# Continuar solo si el DataFrame se cargó correctamente
if 'df' in locals() and df is not None:
    # Información general
    print(df.shape)
    print("\n")
    display(df.head())
    print("\n")
    display(df.info())
    print("\n")
    display(df.describe(include="all"))
else:
    print("El DataFrame 'df' no está cargado. Por favor, asegúrate de ejecutar la celda de carga de datos.")

(500, 21)

,Month,Case_No,DOB,Nationality,Gender,DoctorLicense,DoctorName,Doctor Type,Doctor Status,CMI Value,...,Insurance/Payer,InsurancePlanName,Payer Mix,Case type,LOS,Severity,Surgical Mix,Discharge Time,Discharge Before 12PM,Revenue
0,2025-02-01,123517868.0,2002.0,Pakistan,F,ABC123,Dr. Shawn Martin,Consultant,Inactive,1.048,...,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,07:00:00,Yes,548.0
1,2025-10-01,123810649.0,1981.0,Indonesia,F,VBN123,Dr. Peter Novak,Consultant,Active,0.942,...,PureWin Insurance,Basic,Insurance,OP,0.0,2.0,Medical,NaN,NaN,1198.0
2,2025-08-01,123979661.0,1990.0,Egypt,M,FGH123,Dr. Sofia Kim,GP,Active,1.089,...,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,NaN,NaN,586.0
3,2025-06-01,123927914.0,1991.0,Germany,M,HJK123,Dr. Priya Iyer,Specialist,Active,0.970,...,BlueMedic Charity,NaN,Corporate,IP,5.0,1.0,Medical,09:13:00,Yes,28717.0
4,2025-06-01,123605097.0,2000.0,UAE,F,ABC234,Dr. Thomas Muller,Specialist,Active,1.006,...,Nextcare Insurance,NC-Blue,Insurance,IP,4.0,3.0,Medical,13:39:00,No,117129.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Month                  500 non-null    object
 1   Case_No                500 non-null    float64
 2   DOB                    500 non-null    float64
 3   Nationality            500 non-null    object
 4   Gender                 500 non-null    object
 5   DoctorLicense          500 non-null    object
 6   DoctorName             500 non-null    object
 7   Doctor Type            500 non-null    object
 8   Doctor Status          500 non-null    object
 9   CMI Value              500 non-null    float64
 10  Specialty              500 non-null    object
 11  Insurance/Payer        500 non-null    object
 12  InsurancePlanName      428 non-null    object
 13  Payer Mix              500 non-null    object
 14  Case type              500 non-null    object
 15  LOS                    500 non-null    float64
 16  Severity               500 non-null    float64
 17  Surgical Mix           500 non-null    object
 18  Discharge Time         262 non-null    object
 19  Discharge Before 12PM  262 non-null    object
 20  Revenue                500 non-null    float64
dtypes: float64(6), object(15)
memory usage: 82.2+ KB

None

,Month,Case_No,DOB,Nationality,Gender,DoctorLicense,DoctorName,Doctor Type,Doctor Status,CMI Value,...,Insurance/Payer,InsurancePlanName,Payer Mix,Case type,LOS,Severity,Surgical Mix,Discharge Time,Discharge Before 12PM,Revenue
count,500,5.000000e+02,500.000000,500,500,500,500,500,500,500.000000,...,500,428,500,500,500.000,500.000000,500,262,262,500.00000
unique,12,NaN,NaN,14,2,10,10,3,2,NaN,...,6,9,2,3,NaN,NaN,2,228,2,NaN
top,2025-02-01,NaN,NaN,India,M,FGH234,Dr. Hana Suzuki,Specialist,Active,NaN,...,PureWin Insurance,Advance,Insurance,OP,NaN,NaN,Medical,07:00:00,No,NaN
freq,56,NaN,NaN,101,290,70,70,236,405,NaN,...,211,84,428,308,NaN,NaN,300,2,141,NaN
mean,NaN,1.237317e+08,1984.408000,NaN,NaN,NaN,NaN,NaN,NaN,1.037098,...,NaN,NaN,NaN,NaN,1.284,1.782000,NaN,NaN,NaN,17046.72800
std,NaN,1.585829e+05,14.024225,NaN,NaN,NaN,NaN,NaN,NaN,0.110963,...,NaN,NaN,NaN,NaN,1.946,0.712384,NaN,NaN,NaN,30527.29352
min,NaN,1.234584e+08,1955.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.710000,...,NaN,NaN,NaN,NaN,0.000,1.000000,NaN,NaN,NaN,99.00000
25%,NaN,1.235896e+08,1975.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.960000,...,NaN,NaN,NaN,NaN,0.000,1.000000,NaN,NaN,NaN,830.00000
50%,NaN,1.237408e+08,1987.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.035000,...,NaN,NaN,NaN,NaN,0.000,2.000000,NaN,NaN,NaN,1628.50000
75%,NaN,1.238734e+08,1996.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.110250,...,NaN,NaN,NaN,NaN,3.000,2.000000,NaN,NaN,NaN,15310.50000
max,NaN,1.239995e+08,2005.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.394000,...,NaN,NaN,NaN,NaN,7.000,3.000000,NaN,NaN,NaN,160962.00000

### 5. Limpieza y estandarización de nombres de columnas

Estandarizamos los nombres de las columnas para facilitar el manejo.

In [5]:
if 'df' in locals() and df is not None:
    # Limpieza profesional de nombres de columnas
    df.columns = (
        df.columns
          .str.strip() # Elimina espacios en blanco al inicio y final
          .str.lower() # Convierte a minúsculas
          .str.replace(" ", "_", regex=False) # Reemplaza espacios con guiones bajos
          .str.replace("/", "_", regex=False) # Reemplaza barras con guiones bajos
          .str.replace("-", "_", regex=False) # Reemplaza guiones con guiones bajos
          .str.replace("__", "_", regex=False) # Reemplaza dobles guiones bajos con uno solo (por si acaso)
    )

    print("Nombres de columnas estandarizados:")
    print(df.columns.tolist())
else:
    print("El DataFrame 'df' no está cargado. Por favor, asegúrate de ejecutar la celda de carga de datos.")

Nombres de columnas estandarizados:
['month', 'case_no', 'dob', 'nationality', 'gender', 'doctorlicense', 'doctorname', 'doctor_type', 'doctor_status', 'cmi_value', 'specialty', 'insurance_payer', 'insuranceplanname', 'payer_mix', 'case_type', 'los', 'severity', 'surgical_mix', 'discharge_time', 'discharge_before_12pm', 'revenue']

### 6. Revisión de valores nulos y duplicados

In [6]:
if 'df' in locals() and df is not None:
    # Valores nulos
    nulos = df.isnull().sum().sort_values(ascending=False)
    print("Valores nulos por columna:")
    display(nulos[nulos > 0])

    # Duplicados
    print("\nDuplicados:\n", df.duplicated().sum())

    # Tipos de datos
    print("\nTipos de datos:\n")
    display(df.dtypes)
else:
    print("El DataFrame 'df' no está cargado. Por favor, asegúrate de ejecutar la celda de carga de datos.")

Valores nulos por columna:

discharge_time           238
discharge_before_12pm    238
insuranceplanname         72
dtype: int64

Duplicados:
 0

Tipos de datos:

month                     object
case_no                  float64
dob                      float64
nationality               object
gender                    object
doctorlicense             object
doctorname                object
doctor_type               object
doctor_status             object
cmi_value                float64
specialty                 object
insurance_payer           object
insuranceplanname         object
payer_mix                 object
case_type                 object
los                      float64
severity                 float64
surgical_mix              object
discharge_time            object
discharge_before_12pm     object
revenue                  float64
dtype: object

### 7. Conversión y Validación de Columnas de Fecha

Convertir columnas que representan fechas a un formato `datetime` es crucial para análisis temporales. También validaremos que los identificadores numéricos sean del tipo correcto.

In [7]:
# Detectar automáticamente posibles columnas de fecha

if 'df' in locals() and df is not None:

    date_columns = []

    for col in df.select_dtypes(include='object').columns:

        # Intentar convertir sin mostrar warnings
        converted = pd.to_datetime(
            df[col],
            errors='coerce',
            format='mixed'
        )

        porcentaje_fecha = converted.notna().mean()

        # Si al menos el 70% puede interpretarse como fecha
        if porcentaje_fecha >= 0.70:
            df[col] = converted
            date_columns.append(col)

    print("Columnas detectadas como fecha:")

    if date_columns:
        for col in date_columns:
            print(f"✓ {col}")
    else:
        print("No se detectaron columnas de fecha.")

Columnas detectadas como fecha:
✓ month

In [8]:
# Clasificar automáticamente las columnas del dataset

numeric_columns = df.select_dtypes(include='number').columns.tolist()
categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()
datetime_columns = df.select_dtypes(include=['datetime', 'datetimetz']).columns.tolist()

print("=== CLASIFICACIÓN DE COLUMNAS ===")

print("\nNuméricas:")
print(numeric_columns if numeric_columns else "Ninguna")

print("\nCategóricas / texto:")
print(categorical_columns if categorical_columns else "Ninguna")

print("\nFechas:")
print(datetime_columns if datetime_columns else "Ninguna")

=== CLASIFICACIÓN DE COLUMNAS ===

Numéricas:
['case_no', 'dob', 'cmi_value', 'los', 'severity', 'revenue']

Categóricas / texto:
['nationality', 'gender', 'doctorlicense', 'doctorname', 'doctor_type', 'doctor_status', 'specialty', 'insurance_payer', 'insuranceplanname', 'payer_mix', 'case_type', 'surgical_mix', 'discharge_time', 'discharge_before_12pm']

Fechas:
['month']

### 8. Estandarización de Datos Categóricos

Aseguramos que los valores en columnas categóricas sean consistentes, por ejemplo, convirtiendo a minúsculas o reemplazando variantes.

In [9]:
# Estandarización automática de variables categóricas

for col in df.select_dtypes(include=['object', 'category']).columns:

    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )

print("=== VARIABLES CATEGÓRICAS ESTANDARIZADAS ===")

categorical_cols = df.select_dtypes(
    include=['object', 'category']
).columns.tolist()

print(categorical_cols if categorical_cols else "No se detectaron variables categóricas.")

=== VARIABLES CATEGÓRICAS ESTANDARIZADAS ===
['nationality', 'gender', 'doctorlicense', 'doctorname', 'doctor_type', 'doctor_status', 'specialty', 'insurance_payer', 'insuranceplanname', 'payer_mix', 'case_type', 'surgical_mix', 'discharge_time', 'discharge_before_12pm']

In [10]:
# Perfil automático de calidad de datos

quality_report = pd.DataFrame({
    'columna': df.columns,
    'tipo': df.dtypes.astype(str).values,
    'nulos': df.isnull().sum().values,
    'nulos_%': (df.isnull().mean() * 100).round(2).values,
    'unicos': df.nunique(dropna=False).values
})

quality_report['duplicados_dataset'] = df.duplicated().sum()

print("=== REPORTE DE CALIDAD ===")
display(quality_report)

print("\nFilas duplicadas:", df.duplicated().sum())
print("Total de filas:", len(df))
print("Total de columnas:", len(df.columns))

=== REPORTE DE CALIDAD ===

,columna,tipo,nulos,nulos_%,unicos,duplicados_dataset
0,month,datetime64[ns],0,0.0,12,0
1,case_no,float64,0,0.0,498,0
2,dob,float64,0,0.0,51,0
3,nationality,object,0,0.0,14,0
4,gender,object,0,0.0,2,0
5,doctorlicense,object,0,0.0,10,0
6,doctorname,object,0,0.0,10,0
7,doctor_type,object,0,0.0,3,0
8,doctor_status,object,0,0.0,2,0
9,cmi_value,float64,0,0.0,292,0
10,specialty,object,0,0.0,10,0
11,insurance_payer,object,0,0.0,6,0
12,insuranceplanname,object,0,0.0,10,0
13,payer_mix,object,0,0.0,2,0
14,case_type,object,0,0.0,3,0
15,los,float64,0,0.0,8,0
16,severity,float64,0,0.0,3,0
17,surgical_mix,object,0,0.0,2,0
18,discharge_time,object,0,0.0,229,0
19,discharge_before_12pm,object,0,0.0,3,0
20,revenue,float64,0,0.0,482,0

Filas duplicadas: 0
Total de filas: 500
Total de columnas: 21

In [11]:
# Detectar automáticamente el rol probable de cada columna

column_roles = []

for col in df.columns:

    unique_ratio = df[col].nunique(dropna=False) / len(df)
    col_lower = col.lower()

    # Fecha
    if pd.api.types.is_datetime64_any_dtype(df[col]):
        role = "fecha"

    # Posible ID: alta unicidad + nombre compatible con identificador
    elif (
        unique_ratio >= 0.95
        and any(x in col_lower for x in ['id', 'code', 'codigo', 'case_no', 'number', 'numero'])
    ):
        role = "posible_id"

    # Numéricas
    elif pd.api.types.is_numeric_dtype(df[col]):

        if df[col].nunique() <= 10:
            role = "numerica_discreta"
        else:
            role = "numerica_continua"

    # Texto / categorías
    else:

        if df[col].nunique() <= 20:
            role = "categorica"
        else:
            role = "texto_alta_cardinalidad"

    column_roles.append({
        "columna": col,
        "rol_probable": role,
        "valores_unicos": df[col].nunique(),
        "ratio_unicidad": round(unique_ratio, 3)
    })

roles_report = pd.DataFrame(column_roles)

print("=== ROLES PROBABLES DE LAS COLUMNAS ===")
display(roles_report)

=== ROLES PROBABLES DE LAS COLUMNAS ===

,columna,rol_probable,valores_unicos,ratio_unicidad
0,month,fecha,12,0.024
1,case_no,posible_id,498,0.996
2,dob,numerica_continua,51,0.102
3,nationality,categorica,14,0.028
4,gender,categorica,2,0.004
5,doctorlicense,categorica,10,0.020
6,doctorname,categorica,10,0.020
7,doctor_type,categorica,3,0.006
8,doctor_status,categorica,2,0.004
9,cmi_value,numerica_continua,292,0.584
10,specialty,categorica,10,0.020
11,insurance_payer,categorica,6,0.012
12,insuranceplanname,categorica,10,0.020
13,payer_mix,categorica,2,0.004
14,case_type,categorica,3,0.006
15,los,numerica_discreta,8,0.016
16,severity,numerica_discreta,3,0.006
17,surgical_mix,categorica,2,0.004
18,discharge_time,texto_alta_cardinalidad,229,0.458
19,discharge_before_12pm,categorica,3,0.006
20,revenue,numerica_continua,482,0.964

In [12]:
# Seleccionar automáticamente variables útiles para análisis

ids = roles_report.loc[
    roles_report['rol_probable'] == 'posible_id',
    'columna'
].tolist()

fechas = roles_report.loc[
    roles_report['rol_probable'] == 'fecha',
    'columna'
].tolist()

categoricas = roles_report.loc[
    roles_report['rol_probable'] == 'categorica',
    'columna'
].tolist()

numericas = roles_report.loc[
    roles_report['rol_probable'].isin(
        ['numerica_continua', 'numerica_discreta']
    ),
    'columna'
].tolist()

print("=== VARIABLES DISPONIBLES PARA ANÁLISIS ===")

print("\nIDs (se excluyen del análisis):")
print(ids if ids else "Ninguno")

print("\nFechas:")
print(fechas if fechas else "Ninguna")

print("\nCategóricas:")
print(categoricas if categoricas else "Ninguna")

print("\nNuméricas:")
print(numericas if numericas else "Ninguna")

=== VARIABLES DISPONIBLES PARA ANÁLISIS ===

IDs (se excluyen del análisis):
['case_no']

Fechas:
['month']

Categóricas:
['nationality', 'gender', 'doctorlicense', 'doctorname', 'doctor_type', 'doctor_status', 'specialty', 'insurance_payer', 'insuranceplanname', 'payer_mix', 'case_type', 'surgical_mix', 'discharge_before_12pm']

Numéricas:
['dob', 'cmi_value', 'los', 'severity', 'revenue']

In [13]:
# Evaluar potencial analítico de las variables

analysis_candidates = []

for col in df.columns:

    role = roles_report.loc[
        roles_report['columna'] == col,
        'rol_probable'
    ].values[0]

    score = 0
    motivos = []

    if role == "fecha":
        score += 2
        motivos.append("permite análisis temporal")

    elif role == "categorica":
        unique_count = df[col].nunique()

        if 2 <= unique_count <= 15:
            score += 3
            motivos.append("buena segmentación")

        elif unique_count <= 30:
            score += 2
            motivos.append("segmentación posible")

    elif role in ["numerica_continua", "numerica_discreta"]:
        score += 3
        motivos.append("permite métricas y comparaciones")

        if df[col].std() > 0:
            score += 1
            motivos.append("presenta variabilidad")

    elif role == "posible_id":
        motivos.append("identificador; baja utilidad analítica directa")

    analysis_candidates.append({
        "columna": col,
        "rol": role,
        "score_analitico": score,
        "motivos": ", ".join(motivos)
    })

potential_report = pd.DataFrame(analysis_candidates)

potential_report = potential_report.sort_values(
    by="score_analitico",
    ascending=False
)

print("=== POTENCIAL ANALÍTICO DE LAS VARIABLES ===")
display(potential_report)

=== POTENCIAL ANALÍTICO DE LAS VARIABLES ===

,columna,rol,score_analitico,motivos
2,dob,numerica_continua,4,"permite métricas y comparaciones, presenta var..."
16,severity,numerica_discreta,4,"permite métricas y comparaciones, presenta var..."
15,los,numerica_discreta,4,"permite métricas y comparaciones, presenta var..."
20,revenue,numerica_continua,4,"permite métricas y comparaciones, presenta var..."
9,cmi_value,numerica_continua,4,"permite métricas y comparaciones, presenta var..."
12,insuranceplanname,categorica,3,buena segmentación
11,insurance_payer,categorica,3,buena segmentación
3,nationality,categorica,3,buena segmentación
4,gender,categorica,3,buena segmentación
8,doctor_status,categorica,3,buena segmentación
5,doctorlicense,categorica,3,buena segmentación
7,doctor_type,categorica,3,buena segmentación
6,doctorname,categorica,3,buena segmentación
13,payer_mix,categorica,3,buena segmentación
17,surgical_mix,categorica,3,buena segmentación
10,specialty,categorica,3,buena segmentación
14,case_type,categorica,3,buena segmentación
19,discharge_before_12pm,categorica,3,buena segmentación
0,month,fecha,2,permite análisis temporal
1,case_no,posible_id,0,identificador; baja utilidad analítica directa
18,discharge_time,texto_alta_cardinalidad,0,

In [14]:
# Buscar relaciones prometedoras con medidas comparables

promising_relations = []

# 1. Numérica vs categórica: Eta cuadrado
for num_col in numericas:
    for cat_col in categoricas:

        if 2 <= df[cat_col].nunique() <= 15:

            temp = df[[num_col, cat_col]].dropna()

            if len(temp) > 1:

                media_general = temp[num_col].mean()

                ss_total = ((temp[num_col] - media_general) ** 2).sum()

                ss_between = sum(
                    len(grupo) * (grupo[num_col].mean() - media_general) ** 2
                    for _, grupo in temp.groupby(cat_col)
                )

                if ss_total > 0:
                    eta2 = ss_between / ss_total

                    if eta2 >= 0.05:
                        promising_relations.append({
                            "tipo": "numerica_vs_categorica",
                            "variable_1": num_col,
                            "variable_2": cat_col,
                            "fuerza": round(eta2, 3),
                            "motivo": "diferencias relevantes entre categorías"
                        })

# 2. Numérica vs numérica: correlación
for i in range(len(numericas)):
    for j in range(i + 1, len(numericas)):

        col1 = numericas[i]
        col2 = numericas[j]

        corr = df[[col1, col2]].corr().iloc[0, 1]

        if pd.notna(corr) and abs(corr) >= 0.30:
            promising_relations.append({
                "tipo": "numerica_vs_numerica",
                "variable_1": col1,
                "variable_2": col2,
                "fuerza": round(abs(corr), 3),
                "motivo": f"correlación {round(corr, 2)}"
            })

relations_report = pd.DataFrame(promising_relations)

print("=== RELACIONES PROMETEDORAS ===")

if relations_report.empty:
    print("No se detectaron relaciones destacables.")
else:
    relations_report = relations_report.sort_values(
        by="fuerza",
        ascending=False
    )

    display(relations_report.head(20))

=== RELACIONES PROMETEDORAS ===

,tipo,variable_1,variable_2,fuerza,motivo
2,numerica_vs_categorica,los,case_type,0.902,diferencias relevantes entre categorías
6,numerica_vs_numerica,los,revenue,0.774,correlación 0.77
4,numerica_vs_categorica,revenue,case_type,0.650,diferencias relevantes entre categorías
3,numerica_vs_categorica,los,discharge_before_12pm,0.263,diferencias relevantes entre categorías
5,numerica_vs_categorica,revenue,discharge_before_12pm,0.157,diferencias relevantes entre categorías
1,numerica_vs_categorica,cmi_value,surgical_mix,0.107,diferencias relevantes entre categorías
0,numerica_vs_categorica,cmi_value,case_type,0.059,diferencias relevantes entre categorías

In [15]:
# Generar candidatos de hallazgo en lenguaje natural

hallazgos = []

for _, row in relations_report.iterrows():

    tipo = row["tipo"]
    var1 = row["variable_1"]
    var2 = row["variable_2"]
    fuerza = row["fuerza"]

    if tipo == "numerica_vs_categorica":

        if fuerza >= 0.50:
            nivel = "muy marcada"
        elif fuerza >= 0.20:
            nivel = "moderada"
        else:
            nivel = "leve"

        texto = (
            f"La variable '{var1}' presenta una diferencia {nivel} "
            f"según las categorías de '{var2}' "
            f"(fuerza = {fuerza})."
        )

    elif tipo == "numerica_vs_numerica":

        if fuerza >= 0.70:
            nivel = "fuerte"
        elif fuerza >= 0.50:
            nivel = "moderada"
        else:
            nivel = "débil"

        texto = (
            f"Existe una relación {nivel} entre '{var1}' y '{var2}' "
            f"(fuerza = {fuerza})."
        )

    hallazgos.append({
        "variable_1": var1,
        "variable_2": var2,
        "fuerza": fuerza,
        "candidato_hallazgo": texto
    })

hallazgos_report = pd.DataFrame(hallazgos)

print("=== CANDIDATOS DE HALLAZGO ===")

if hallazgos_report.empty:
    print("No se generaron candidatos de hallazgo.")
else:
    display(hallazgos_report)

=== CANDIDATOS DE HALLAZGO ===

,variable_1,variable_2,fuerza,candidato_hallazgo
0,los,case_type,0.902,La variable 'los' presenta una diferencia muy ...
1,los,revenue,0.774,Existe una relación fuerte entre 'los' y 'reve...
2,revenue,case_type,0.650,La variable 'revenue' presenta una diferencia ...
3,los,discharge_before_12pm,0.263,La variable 'los' presenta una diferencia mode...
4,revenue,discharge_before_12pm,0.157,La variable 'revenue' presenta una diferencia ...
5,cmi_value,surgical_mix,0.107,La variable 'cmi_value' presenta una diferenci...
6,cmi_value,case_type,0.059,La variable 'cmi_value' presenta una diferenci...

In [16]:
# Generar evidencia automática para los candidatos de hallazgo

evidencias = []

for _, row in relations_report.iterrows():

    tipo = row["tipo"]
    var1 = row["variable_1"]
    var2 = row["variable_2"]
    fuerza = row["fuerza"]

    if tipo == "numerica_vs_categorica":

        resumen = (
            df.groupby(var2)[var1]
            .agg(["count", "mean", "median"])
            .round(2)
            .reset_index()
            .sort_values("mean", ascending=False)
        )

        top = resumen.iloc[0]
        bottom = resumen.iloc[-1]

        evidencias.append({
            "variable_1": var1,
            "variable_2": var2,
            "fuerza": fuerza,
            "evidencia": (
                f"Mayor promedio: {top[var2]} = {top['mean']}. "
                f"Menor promedio: {bottom[var2]} = {bottom['mean']}. "
                f"Diferencia = {round(top['mean'] - bottom['mean'], 2)}."
            )
        })

    elif tipo == "numerica_vs_numerica":

        corr = df[[var1, var2]].corr().iloc[0, 1]

        evidencias.append({
            "variable_1": var1,
            "variable_2": var2,
            "fuerza": fuerza,
            "evidencia": (
                f"Correlación = {round(corr, 2)}. "
                f"A mayor '{var1}', {'tiende a aumentar' if corr > 0 else 'tiende a disminuir'} '{var2}'."
            )
        })

evidence_report = pd.DataFrame(evidencias)

print("=== EVIDENCIA DE LOS CANDIDATOS ===")

if evidence_report.empty:
    print("No se generó evidencia.")
else:
    display(evidence_report)

=== EVIDENCIA DE LOS CANDIDATOS ===

,variable_1,variable_2,fuerza,evidencia
0,los,case_type,0.902,Mayor promedio: ip = 4.19. Menor promedio: op ...
1,los,revenue,0.774,"Correlación = 0.77. A mayor 'los', tiende a au..."
2,revenue,case_type,0.650,Mayor promedio: ip = 56212.91. Menor promedio:...
3,los,discharge_before_12pm,0.263,Mayor promedio: yes = 2.31. Menor promedio: na...
4,revenue,discharge_before_12pm,0.157,Mayor promedio: no = 29519.24. Menor promedio:...
5,cmi_value,surgical_mix,0.107,Mayor promedio: surgery = 1.08. Menor promedio...
6,cmi_value,case_type,0.059,Mayor promedio: ip = 1.08. Menor promedio: op ...

In [17]:
# Puntuar candidatos de hallazgo

scored_findings = []

for _, row in evidence_report.iterrows():

    fuerza = row["fuerza"]
    var1 = row["variable_1"]
    var2 = row["variable_2"]
    evidencia = row["evidencia"]

    score = 0

    # Fuerza estadística
    if fuerza >= 0.70:
        score += 3
    elif fuerza >= 0.40:
        score += 2
    elif fuerza >= 0.10:
        score += 1

    # Variables numéricas o categóricas útiles
    if var1 in numericas:
        score += 1

    if var2 in categoricas or var2 in numericas:
        score += 1

    # Clasificación final
    if score >= 5:
        nivel = "Hallazgo fuerte"
    elif score >= 3:
        nivel = "Hallazgo medio"
    else:
        nivel = "Exploratorio"

    scored_findings.append({
        "variable_1": var1,
        "variable_2": var2,
        "fuerza": fuerza,
        "score": score,
        "nivel": nivel,
        "evidencia": evidencia
    })

findings_score_report = pd.DataFrame(scored_findings)

findings_score_report = findings_score_report.sort_values(
    by=["score", "fuerza"],
    ascending=False
)

print("=== RANKING DE HALLAZGOS ===")

if findings_score_report.empty:
    print("No se encontraron hallazgos.")
else:
    display(findings_score_report)

=== RANKING DE HALLAZGOS ===

,variable_1,variable_2,fuerza,score,nivel,evidencia
0,los,case_type,0.902,5,Hallazgo fuerte,Mayor promedio: ip = 4.19. Menor promedio: op ...
1,los,revenue,0.774,5,Hallazgo fuerte,"Correlación = 0.77. A mayor 'los', tiende a au..."
2,revenue,case_type,0.650,4,Hallazgo medio,Mayor promedio: ip = 56212.91. Menor promedio:...
3,los,discharge_before_12pm,0.263,3,Hallazgo medio,Mayor promedio: yes = 2.31. Menor promedio: na...
4,revenue,discharge_before_12pm,0.157,3,Hallazgo medio,Mayor promedio: no = 29519.24. Menor promedio:...
5,cmi_value,surgical_mix,0.107,3,Hallazgo medio,Mayor promedio: surgery = 1.08. Menor promedio...
6,cmi_value,case_type,0.059,2,Exploratorio,Mayor promedio: ip = 1.08. Menor promedio: op ...

In [18]:
# Evaluar aptitud del dataset para un caso BI / portfolio

score = 0
criterios = []

# Tamaño
if len(df) >= 5000:
    score += 2
    criterios.append("Buen volumen de registros")
elif len(df) >= 500:
    score += 1
    criterios.append("Volumen aceptable")
else:
    criterios.append("Dataset pequeño")

# Variedad de columnas
if len(df.columns) >= 10:
    score += 1
    criterios.append("Buena variedad de variables")

# Variables numéricas
if len(numericas) >= 2:
    score += 2
    criterios.append("Tiene métricas suficientes")

# Variables categóricas
if len(categoricas) >= 2:
    score += 2
    criterios.append("Permite segmentación")

# Fechas
if len(fechas) >= 1:
    score += 1
    criterios.append("Permite análisis temporal")

# Relaciones prometedoras
hallazgos_fuertes = len(
    findings_score_report[
        findings_score_report["nivel"] == "Hallazgo fuerte"
    ]
)

hallazgos_medios = len(
    findings_score_report[
        findings_score_report["nivel"] == "Hallazgo medio"
    ]
)

if hallazgos_fuertes >= 2:
    score += 2
    criterios.append("Tiene varios hallazgos fuertes")
elif hallazgos_fuertes >= 1 or hallazgos_medios >= 2:
    score += 1
    criterios.append("Tiene potencial analítico")

# Clasificación final
if score >= 8:
    resultado = "MUY APTO PARA PORTFOLIO"
elif score >= 6:
    resultado = "APTO PARA PORTFOLIO"
elif score >= 4:
    resultado = "APTITUD MEDIA - REVISAR"
else:
    resultado = "POCO APTO PARA PORTFOLIO"

print("=== PORTFOLIO SCORE ===")
print(f"\nScore: {score}/10")
print(f"Resultado: {resultado}")

print("\nCriterios:")
for criterio in criterios:
    print("•", criterio)

=== PORTFOLIO SCORE ===

Score: 9/10
Resultado: MUY APTO PARA PORTFOLIO

Criterios:
• Volumen aceptable
• Buena variedad de variables
• Tiene métricas suficientes
• Permite segmentación
• Permite análisis temporal
• Tiene varios hallazgos fuertes